image: node:9.11.1

pages:
 cache:
   paths:
   - node_modules/

 script:
 - npm install # npm install
 - npm run build # npm run docs:build
 - npm run deploy
 artifacts:
   paths:
   - public
 only:
 - gh:pages