name: check
on: [push]
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
    - name: Checkout    
      uses: actions/checkout@v2 
      
    - name: Install Dependencies
      run: npm install
    - name: lint
      run: npm run build
    - name: test
      run: npm run deploy
