name: check
on: [push]
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
    - name: Checkout    
      uses: actions/checkout@v2 
    - name: deploy
      run: npm run deploy
